import { RouteRecordRaw } from "vue-router"
export default {
    name:'Home',
    path:'/',
    redirect:'/home',
    component:()=>import('@/layouts/Home.vue'),
    children:[
        {
            name:'home',
            path:'',
            component:()=>import('@/views/Home/Home/index.vue'),
        },
        {
            path:'/login',
            name:'login',
            component:()=>import('@/views/Home/Login/index.vue'),
            meta:{guest:true}
        },
        {
            path:'/register',
            name:'register',
            component:()=>import('@/views/Home/Register/index.vue'),
        },
        {
            path:'/search/:keyword?',
            name:'search',
            component:()=>import('@/views/Home/Search/index.vue'),
            props:true
        },
        {
            path:'/detail/:skuId',
            name:'detail',
            component:()=>import('@/views/Home/Detail/index.vue'),
        },
        {
            path:'/addcartsuccess',
            name:'addCartSuccess',
            component:()=>import('@/views/Home/AddCartSuccess/index.vue'),
            meta:{auth:true}
        },
        {
            path:'/shopcart',
            name:'shopCart',
            component:()=>import('@/views/Home/ShopCart/index.vue'),
            meta:{auth:true}
        },
        {
            path:'/trade',
            name:'trade',
            component:()=>import('@/views/Home/Trade/index.vue'),
            meta:{auth:true},
            beforeEnter:(to,from,next)=>{
                if(from.name==='shopCart'){
                    next()
                }else{
                    next(from)
                }
            }
        },
        {
            path:'/pay',
            name:'pay',
            component:()=>import('@/views/Home/Pay/index.vue'),
            meta:{auth:true},
            beforeEnter:(to,from,next)=>{
                if(from.name==='trade'){
                    next()
                }else{
                    next(from)
                }
            }
        },
        {
            path:'/payseccess',
            name:'paySuccess',
            component:()=>import('@/views/Home/PaySuccess/index.vue'),
            meta:{auth:true},
            beforeEnter:(to,from,next)=>{
                if(from.name==='pay'){
                    next()
                }else{
                    next(from)
                }
            }
        },
        {
            path:'/center',
            name:'center',
            component:()=>import('@/views/Home/Center/index.vue'),
            meta:{auth:true},
            redirect:'/center/myorder',
            children:[
                {
                    path:'myorder',
                    name:'myOrder',
                    component:()=>import('@/views/Home/Center/myOrder/index.vue'),
                },
                {
                    path:'grouporder',
                    name:'groupOrder',
                    component:()=>import('@/views/Home/Center/groupOrder/index.vue'),
                },
            ]
        },
    ]
} as RouteRecordRaw